### ISSUE TITLE
Dockerize API and Integrate BERT/FastText Models for Easy Deployment

### ISSUE THREAD

**Issue by ajamous** [TelecomsXChangeAPi/OpenTextShield#1]
#### Description
We aim to simplify the deployment process of our FastAPI application, which serves as an interface to our BERT and FastText models for SMS classification. The current setup process is manual and requires several steps, including setting up Python environments, installing dependencies, and loading pre-trained models. To enhance usability and facilitate a smoother setup for developers and users alike, we propose dockerizing the application along with the BERT and FastText models.

#### Objective
- **Dockerize the FastAPI application**: Package the FastAPI application into a Docker container, encapsulating its dependencies and runtime environment to ensure consistency across different setups.
- **Integrate OTS BERT and FastText models**: Ensure the Docker container has access to the pre-trained BERT and FastText models, enabling the API to perform SMS classification without additional setup.
- **Simplify deployment**: Allow users to deploy the application with minimal setup, ideally with a single command or a few simple steps.

#### Tasks
- [ ] Create a `Dockerfile` that specifies the environment, installs dependencies, and sets up the application.
- [ ] Ensure the Docker container can access the BERT and FastText models, either by bundling them with the container or by implementing a mechanism to load them on startup.
- [ ] Write documentation explaining how to build and run the Docker container, including how to access the API and perform classifications.
- [ ] Test the Docker setup on different platforms (e.g., Linux, macOS, Windows) to ensure compatibility and ease of use.

#### Requirements
- The Docker container should be based on a lightweight, secure base image (e.g., Python Alpine).
- Include comments in the `Dockerfile` and documentation to guide new users through the Docker setup and deployment process.
- Ensure the API's performance and responsiveness are not negatively impacted by containerization.
- Consider security best practices for Docker deployment, especially regarding data handling and network configurations.

#### Discussion Points
- **Model Storage**: Discuss whether to bundle the models within the Docker image or to download them dynamically upon container startup. Consider trade-offs in terms of image size, startup time, and flexibility.
- **Configuration Management**: Explore options for configuring the API and models within the Docker environment, possibly using environment variables or external configuration files.

#### Contributions
Contributions are welcome, and this issue serves as a starting point for discussion, planning, and implementation. If you have experience with Docker, Python environments, or have insights into deploying machine learning models in production, your input would be highly valued.

**Comment by ajamous** [comment]
Good news! Now OTS is dockerized with pre-trained models bundled in. You can now deploy a working OTS in just a few minutes and start making predictions on any text you provide.

## Quick Start with Docker

Setting up **Open Text Shield** is quick and easy with Docker. Follow these steps to get started:

### 1. Pull the Latest Docker Image
```bash
docker pull telecomsxchange/opentextshield:latest
```

### 2. Run the Docker Container
```bash
docker run -d -p 8002:8002 telecomsxchange/opentextshield:latest
```

### 3. Send a Message for Prediction
Once the container is running, you can send HTTP requests to the API to classify messages.

Example `curl` request:
```bash
curl -X POST "http://localhost:8002/predict/" \
-H "accept: application/json" \
-H "Content-Type: application/json" \
-d "{\"text\":\"Your SMS content here\",\"model\":\"bert\"}"
```

### Example Response:
```json
{
  "label": "ham",
  "probability": 0.9971883893013,
  "processing_time": 0.6801116466522217,
  "Model_Name": "OTS_mBERT",
  "Model_Version": "bert-base-uncased",
  "Model_Author": "TelecomsXChange (TCXC)",
  "Last_Training": "2024-03-20"
}
```

**Comment by ajamous** [comment]
x86 arch docker image has been released, to use it run : `docker pull telecomsxchange/opentextshield:2.1-x86`
